services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: moriafund_root_pwd
      MYSQL_USER: moriafund_dev
      MYSQL_PASSWORD: moriafund_dev_pwd
      MYSQL_DATABASE: moriafund_dev_db

volumes:
  mysql-data:
