services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - airbnb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: passwrd@321
    networks:
      - airbnb-net

volumes:
  airbnb-data:

networks:
  airbnb-net: