services:
  mongo:
    image: mongo:4
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: yalect
      MONGO_INITDB_ROOT_PASSWORD: "mongo1234"
      MONGO_INITDB_DATABASE: myapp
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network

  # nestjs-app:
  #   build: .  # Assuming you have a Dockerfile in the same directory
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     MONGODB_URI: mongodb://appuser:apppass123@mongo:27017/myapp
  #   depends_on:
  #     - mongo
  #   networks:
  #     - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: yalect
      ME_CONFIG_MONGODB_ADMINPASSWORD: "mongo1234"
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge