# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgresql
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: winnov8
      POSTGRES_PASSWORD: X9khTgSzvqZrMi6WPUtIyAbywUyvjgkd
      POSTGRES_DB: winnov8_db
    ports:
      - 5432:5432
    networks:
      - postgress_network
  
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - postgress_network

volumes:
  postgres_volume:
  pgadmin_volume:

networks:
  postgress_network:
