services:
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin_external
    restart: always
    ports:
      - 5055:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
